services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'pass'
